name: Generate PDF

on:
  # allows manual triggering of the workflow
  workflow_dispatch:
  # run on changes to main
  push:
    branches:
      - main
  # run on PRs to main
  pull_request:
    branches:
      - main

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Build PDF
        uses: xu-cheng/latex-action@v4
        with:
          root_file: M17_spec.tex

      - name: Move PDF to public/
        run: |
          mkdir -p public
          mv M17_spec.pdf public/

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload PDF artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

      - name: Deploy to GitHub Pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/deploy-pages@v4
