name: Generate PDF

on:
  # allows manual triggering of the workflow
  workflow_dispatch:
  # run on changes to main
  push:
    branches:
      - main
  # run on PRs to main
  pull_request:
    branches:
      - main

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Build PDF
        uses: xu-cheng/latex-action@v4
        with:
          root_file: M17_spec.tex

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: specification
          path: M17_spec.pdf

      - name: Deploy to GitHub Pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/deploy-pages@v4
        with:
          artifact_name: specification

      - name: Deploy PR Preview
        if: github.event_name == 'pull_request'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          destination_dir: pr-${{ github.event.number }}
          keep_files: true
