name: Generate PDF

on:
  # allows manual triggering of the workflow
  workflow_dispatch:
  # run on changes to main
  push:
    branches:
      - main
  # run on PRs to main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        uses: xu-cheng/latex-action@v4
        with:
          root_file: M17_spec.tex

      - name: Prepare Pages artifact
        run: |
          mkdir -p public
          cp M17_spec.pdf public/

      - name: Upload Pages artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: public

      - name: Deploy to Pages (main branch only)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/deploy-pages@v4

      - name: Deploy Preview (PR only)
        if: github.event_name == 'pull_request'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          destination_dir: pr-${{ github.event.number }}